/*
 * MainForm.java
 *
 * Created on February 5, 2011, 7:14 PM
 */

package SMS;

import java.awt.Component;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author  Lasitha
 */
public class AdminForm extends javax.swing.JFrame {
    private LogIn logIn;
    private StudentForm studentForm;
     private ClientMnpltn clnt;
     private Component frame;
    /** Creates new form MainForm */
    public AdminForm(LogIn logIn, ClientMnpltn clnt) {
        this.logIn = logIn;
        this.clnt = clnt;
        this.setWindowImage();
        
        initComponents();
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        reportLabel = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        lblImgWindow = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(670, 390));
        getContentPane().setLayout(null);

        jLabel2.setBackground(new java.awt.Color(255, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel2.setText("Well Come To UOM Students Magement System");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 45, 330, 37);

        jButton1.setText("Add Student");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(60, 116, 93, 23);

        jButton2.setText("Edit Student");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(60, 145, 93, 23);

        reportLabel.setText("Reports");
        reportLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportLabelActionPerformed(evt);
            }
        });
        getContentPane().add(reportLabel);
        reportLabel.setBounds(60, 179, 93, 23);

        jButton5.setText("Log out");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(321, 16, 69, 23);
        getContentPane().add(lblImgWindow);
        lblImgWindow.setBounds(0, 0, 580, 230);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    studentForm = new StudentForm(this,clnt);
    System.out.println("Enabling add student mode from Admon form ");
    studentForm.enableAddStudentMode();
    studentForm.setVisible(true);
    this.setVisible(false);
    
    
}//GEN-LAST:event_jButton1ActionPerformed

 public void setWindowImage(){
        try{
            BufferedImage image = ImageIO.read(new File("adminStudent.jpg"));
            System.out.println("read the pic.. ");
            lblImgWindow.setIcon(new ImageIcon(image.getScaledInstance(lblImgWindow.getWidth(), lblImgWindow.getHeight(), BufferedImage.SCALE_AREA_AVERAGING)));
        }catch(Exception e){
            System.out.println("Erroo.. while reading the pictureee.. ");
        }
    }

private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
// TODO add your handling code here:
    logIn.clear();
    logIn.setVisible(true);
    
    this.setVisible(false);
    this.dispose();
}//GEN-LAST:event_jButton5ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
    studentForm = new StudentForm(this,clnt);
    studentForm.enableEditStudentMode();
    studentForm.setVisible(true);
    this.setVisible(false);
    
}//GEN-LAST:event_jButton2ActionPerformed

private void reportLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportLabelActionPerformed
    // TODO add your handling code here:

    int n = JOptionPane.showConfirmDialog(frame,"Are you sure you want to generate Student reports?","Verification",JOptionPane.YES_NO_OPTION);
    if(n== JOptionPane.YES_OPTION){
        JOptionPane.showMessageDialog(frame, "Select the file to save ", "Select", JOptionPane.OK_OPTION);
        String filePath;
        JFileChooser chooser = new JFileChooser();
        //chooser.setAcceptAllFileFilterUsed(false);
        //chooser.setFileFilter(new TextFilter());

        int returnVal = chooser.showOpenDialog(null);
        if(returnVal == JFileChooser.APPROVE_OPTION) {

        filePath =chooser.getSelectedFile().getPath();
        boolean reported;
        try{
        reported= clnt.generateReports(filePath);
        }catch(Exception ex){
            reported = false;
        }
            System.out.println("did report? "+reported);
        if(reported){
            JOptionPane.showMessageDialog(frame, "Report Generated successfully, click ok to continue", "Generated Success", JOptionPane.OK_OPTION);
        }else{
            JOptionPane.showMessageDialog(frame, "Error occured while generating reports", "Error", JOptionPane.OK_OPTION);
        }
    }
    }



}//GEN-LAST:event_reportLabelActionPerformed

    /**
    * @param args the command line arguments
    */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblImgWindow;
    private javax.swing.JButton reportLabel;
    // End of variables declaration//GEN-END:variables

}
