/*
 * StudentManipulation.java
 *
 * Created on February 6, 2011, 6:50 PM
 */

package SMS;

/**
 *
 * @author  Lasitha
 */
import java.awt.Component;
import java.awt.image.BufferedImage;
import java.awt.image.ImageFilter;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

public class StudentManipulation extends javax.swing.JFrame {

    private LogIn logIn;
    private Student student;
     private Component frame;
    private ClientMnpltn clnt;
    private BufferedImage bufImg;
    private byte[] bufImgArray;

    /** Creates new form StudentManipulation */
    public StudentManipulation(Student student,LogIn logIn,ClientMnpltn clnt) {
        this.logIn = logIn;
        this.student = student;
        initComponents();
        this.enableProfileMode(student);
        saveButton.setVisible(false);
        cancelButton.setVisible(false);
        this.clnt = clnt;
    }

    public void enableProfileMode(Student student){
        indexTF.setText(student.getIndex());
        indexTF.setEditable(false);
        nameWithInTF.setText(student.getNameWithIn());
        nameWithInTF.setEditable(false);
        fNameTF.setText(student.getFName());
        fNameTF.setEditable(false);
        String[] dOB = student.getDateOfBirth().split("/");
        yearTF.setText(dOB[0]);
        yearTF.setEditable(false);
        monthTF.setText(dOB[1]);
        monthTF.setEditable(false);
        dateTF.setText(dOB[2]);
        dateTF.setEditable(false);
        genderCB.setSelectedItem(student.getGender());
        genderCB.setEditable(false);
        homeADDTF.setText(student.getHomeAddress());
        homeADDTF.setEditable(false);
        telephoneTF.setText(student.getTelephone());
        telephoneTF.setEditable(false);
        saveButton.setVisible(false);
        cancelButton.setVisible(false);
        passWordLB.setVisible(false);
        passWordF.setVisible(false);
        changeButton.setVisible(false);
        confirmLB.setVisible(false);
        confirmPassWordF.setVisible(false);
        confirmButton.setVisible(false);
        cancelPWchange.setVisible(false);
        changePhoto.setVisible(false);
        setImage(student.getImage());


    }

    public void setImage(byte[] img){
        this.bufImg = this.bytesToImage(img);
        bufImgArray= img;

        photoLabel.setIcon(new ImageIcon(bufImg.getScaledInstance(88, 80, BufferedImage.SCALE_AREA_AVERAGING)));

    }


      public BufferedImage bytesToImage(byte[] byteImage){
        BufferedImage bImageFromConvert = null;
        InputStream in = new ByteArrayInputStream(byteImage);
        try{
	bImageFromConvert = ImageIO.read(in);
        }catch(Exception e){
            System.out.println("byte array error");
        }
        return bImageFromConvert;
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        yearTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        monthTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        dateTF = new javax.swing.JTextField();
        indexTF = new javax.swing.JTextField();
        nameWithInTF = new javax.swing.JTextField();
        fNameTF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        genderCB = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        homeADDTF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        telephoneTF = new javax.swing.JTextField();
        editButton = new javax.swing.JButton();
        logOutButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        passWordLB = new javax.swing.JLabel();
        passWordF = new javax.swing.JPasswordField();
        confirmLB = new javax.swing.JLabel();
        confirmPassWordF = new javax.swing.JPasswordField();
        changeButton = new javax.swing.JButton();
        confirmButton = new javax.swing.JButton();
        cancelPWchange = new javax.swing.JButton();
        photoLabel = new javax.swing.JLabel();
        changePhoto = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Index");

        jLabel2.setText("Name with Initials");

        jLabel3.setText("First Name");

        jLabel4.setText("Birth Day");

        jLabel5.setText("Year ");

        jLabel6.setText("Month");

        jLabel7.setText("Date");

        jLabel8.setText("Gender");

        genderCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Male", "Female" }));
        genderCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderCBActionPerformed(evt);
            }
        });

        jLabel9.setText("Home Address");

        jLabel10.setText("Telephone");

        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        logOutButton.setText("LogOut");
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        passWordLB.setText("PassWord");

        confirmLB.setText("Confirm passWord");

        changeButton.setText("change");
        changeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeButtonActionPerformed(evt);
            }
        });

        confirmButton.setText("Confirm");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        cancelPWchange.setText("Cancel");
        cancelPWchange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelPWchangeActionPerformed(evt);
            }
        });

        changePhoto.setText("Change the Pic");
        changePhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePhotoActionPerformed(evt);
            }
        });

        jLabel11.setText("Profile Pic");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addComponent(saveButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(photoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(changePhoto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(logOutButton)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(233, 233, 233)
                                    .addComponent(dateTF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(fNameTF, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                                        .addComponent(nameWithInTF)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(confirmPassWordF)
                                            .addComponent(passWordF, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(confirmButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cancelPWchange)))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel1))
                                    .addGap(44, 44, 44)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addGap(52, 52, 52)
                                            .addComponent(jLabel6)
                                            .addGap(44, 44, 44)
                                            .addComponent(jLabel7)
                                            .addGap(27, 27, 27))
                                        .addComponent(indexTF, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(genderCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(85, 85, 85)
                                    .addComponent(yearTF, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(28, 28, 28)
                            .addComponent(monthTF, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(telephoneTF, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                                .addComponent(homeADDTF))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(passWordLB))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(confirmLB)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(changeButton)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(photoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(indexTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(nameWithInTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(logOutButton)
                        .addComponent(changePhoto)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passWordLB)
                    .addComponent(passWordF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changeButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmLB)
                    .addComponent(confirmPassWordF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmButton)
                    .addComponent(cancelPWchange))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monthTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(genderCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(homeADDTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(telephoneTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(editButton)
                    .addComponent(cancelButton))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void genderCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderCBActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_genderCBActionPerformed

private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
// TODO add your handling code here:
    this.setVisible(false);
    logIn.setVisible(true);
    this.dispose();
    logIn.clear();
}//GEN-LAST:event_logOutButtonActionPerformed

private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
// TODO add your handling code here:
    this.enableProfileMode(student);
    editButton.setEnabled(true);
}//GEN-LAST:event_cancelButtonActionPerformed

private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
// TODO add your handling code here
    editButton.setEnabled(false);
    saveButton.setVisible(true);
    cancelButton.setVisible(true);
    fNameTF.setEditable(true);
    homeADDTF.setEditable(true);
    telephoneTF.setEditable(true);
    passWordLB.setVisible(true);
    passWordF.setVisible(true);
    passWordF.setEditable(false);
    changeButton.setVisible(true);
    passWordF.setText(logIn.getPassWord());
    changePhoto.setVisible(true);
    
}//GEN-LAST:event_editButtonActionPerformed

private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
// TODO add your handling code here:
    if(fNameTF.getText().equalsIgnoreCase("")|homeADDTF.getText().equalsIgnoreCase("")|telephoneTF.getText().equalsIgnoreCase("")){
         JOptionPane.showMessageDialog(frame,"You are not allowed to leave any text field","Error",JOptionPane.ERROR_MESSAGE);
    }else{
        int n = JOptionPane.showConfirmDialog(frame, "Are you Sure? ", "Veriry", JOptionPane.YES_NO_OPTION);
        if(n==JOptionPane.YES_OPTION){                
                try {

                    Student modStdnt = new Student(indexTF.getText(), nameWithInTF.getText(), fNameTF.getText(), yearTF.getText() + "/" + monthTF.getText() + "/" + dateTF.getText(), (String) genderCB.getSelectedItem(), homeADDTF.getText(), telephoneTF.getText(),bufImgArray);
                    boolean upDated = clnt.upDate(modStdnt);
                    if (upDated) {
                        JOptionPane.showMessageDialog(frame, "SuccessFully Uploaded", "Message", JOptionPane.OK_OPTION);
                        editButton.setEnabled(true);
                        enableProfileMode(modStdnt);
                    } else {
                        JOptionPane.showMessageDialog(frame, "Error while upDating", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                } catch (IOException ex) {
                    Logger.getLogger(StudentManipulation.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(StudentManipulation.class.getName()).log(Level.SEVERE, null, ex);
                }
        }
        
    }
    
    
}//GEN-LAST:event_saveButtonActionPerformed

private void changeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeButtonActionPerformed
// TODO add your handling code here:
    
    passWordF.setEditable(true);
    confirmLB.setVisible(true);
    changeButton.setEnabled(false);
    confirmPassWordF.setVisible(true);
    confirmButton.setVisible(true);
    cancelPWchange.setVisible(true);
}//GEN-LAST:event_changeButtonActionPerformed

private void cancelPWchangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelPWchangeActionPerformed
// TODO add your handling code here:
    confirmLB.setVisible(false);
    confirmPassWordF.setText("");
    confirmPassWordF.setVisible(false);
    confirmButton.setVisible(false);
    cancelPWchange.setVisible(false);
    passWordF.setText(logIn.getPassWord());
    passWordF.setEditable(false);
    changeButton.setEnabled(true);
}//GEN-LAST:event_cancelPWchangeActionPerformed

private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
// TODO add your handling code here:
    if(passWordF.getText().equalsIgnoreCase("")|confirmPassWordF.getText().equalsIgnoreCase("")){
       JOptionPane.showMessageDialog(frame,"Fill all two fields before confirmation","Error",JOptionPane.ERROR_MESSAGE); 
    }else{
        if(passWordF.getText().equalsIgnoreCase(confirmPassWordF.getText())){
            int n = JOptionPane.showConfirmDialog(frame, "Are you Sure? ", "Veriry", JOptionPane.YES_NO_OPTION);
            if(n== JOptionPane.YES_OPTION){
                    try {
                        
                        boolean pWChanged = clnt.changePWord(indexTF.getText(), passWordF.getText());
                        if (pWChanged) {
                            JOptionPane.showMessageDialog(frame, "Password Changed successfully, click ok to continue", "Info", JOptionPane.OK_OPTION);
                            passWordF.setEditable(false);
                            confirmLB.setVisible(false);
                            confirmPassWordF.setText("");
                            confirmPassWordF.setVisible(false);
                            confirmButton.setVisible(false);
                            cancelPWchange.setVisible(false);
                            changeButton.setEnabled(true);
                        } else {
                            JOptionPane.showMessageDialog(frame, "Erro occured,Rechange password", "Error", JOptionPane.ERROR_MESSAGE);
                        }
                    } catch (IOException ex) {
                        Logger.getLogger(StudentManipulation.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(StudentManipulation.class.getName()).log(Level.SEVERE, null, ex);
                    }
            }
            
        }else{
            JOptionPane.showMessageDialog(frame,"Enter the correct password","confirmation Erro",JOptionPane.ERROR_MESSAGE);
        }
    }
    
}//GEN-LAST:event_confirmButtonActionPerformed

private void changePhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePhotoActionPerformed
    // TODO add your handling code here:
      final JFileChooser fc = new JFileChooser();
      fc.setAcceptAllFileFilterUsed(false);
      fc.setFileFilter(new SMS.ImageFilter());

    int status = fc.showOpenDialog(this);

    try {
        if (status == JFileChooser.APPROVE_OPTION) {
            bufImg = ImageIO.read(fc.getSelectedFile());
            this.setImage(this.imageToBytes(bufImg));
            bufImgArray = imageToBytes(bufImg);
        }

    } catch (IOException e) {
        e.printStackTrace();
   }
}//GEN-LAST:event_changePhotoActionPerformed





 public byte[] imageToBytes(BufferedImage img){
        byte[] imageInByte = null;
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        try{
	ImageIO.write( img, "jpg", baos );
	baos.flush();
	imageInByte = baos.toByteArray();
	baos.close();}
        catch(Exception e){

        }
        return imageInByte;
    }

    /**
    * @param args the command line arguments
    */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton cancelPWchange;
    private javax.swing.JButton changeButton;
    private javax.swing.JButton changePhoto;
    private javax.swing.JButton confirmButton;
    private javax.swing.JLabel confirmLB;
    private javax.swing.JPasswordField confirmPassWordF;
    private javax.swing.JTextField dateTF;
    private javax.swing.JButton editButton;
    private javax.swing.JTextField fNameTF;
    private javax.swing.JComboBox genderCB;
    private javax.swing.JTextField homeADDTF;
    private javax.swing.JTextField indexTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton logOutButton;
    private javax.swing.JTextField monthTF;
    private javax.swing.JTextField nameWithInTF;
    private javax.swing.JPasswordField passWordF;
    private javax.swing.JLabel passWordLB;
    private javax.swing.JLabel photoLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField telephoneTF;
    private javax.swing.JTextField yearTF;
    // End of variables declaration//GEN-END:variables

}
